# FLATPAK
abbr maps "flatpak run app.organicmaps.desktop"
abbr obs "flatpak run com.obsproject.Studio"
abbr bottles "flatpak run com.usebottles.bottles"
abbr code "flatpak run com.vscodium.codium"
#abbr exiftool "flatpak run io.github.hvdwofl.jExifToolGUI"
abbr ftpserver "flatpak run eu.ithz.umftpd"
abbr filezilla "flatpak run org.filezillaproject.Filezilla"
abbr freefilesync "flatpak run org.freefilesync.FreeFileSync"
abbr inkscape "flatpak run org.inkscape.Inkscape"
abbr soundjuicer "flatpak run org.gnome.SoundJuicer"
#abbr kfind "flatpak run org.kde.kfind"
abbr kamoso "flatpak run org.kde.kamoso"
abbr kdenlive "flatpak run org.kde.kdenlive"
abbr kleopatra "flatpak run org.kde.kleopara"
abbr krdc "flatpak run org.kde.krdc"
abbr krita "flatpak run org.kde.krita"
abbr konversation "flatpak run org.kde.konversation"
# abbr keepassxc "flatpak run org.keepassxc.KeePassXC"
abbr libreoffice "flatpak run org.libreoffice.LibreOffice"
#abbr firefox "flatpak run org.mozilla.firefox"
abbr octave "flapak run org.octave.Octave"
abbr onionshare "flatpak run org.onionshare.OnionShare"
abbr tor-browser "flatpak run com.github.micahflee.torbrowser-launcher"
abbr torbrowser "flatpak run com.github.micahflee.torbrowser-launcher"
abbr betterbird "flatpak run eu.betterbird.Betterbird"
abbr element "flatpak run im.riot.Riot"
abbr handbrake "flatpak run fr.handbrake.ghb"
abbr xnview "flatpak run com.xnview.XnViewMP"
abbr xnconvert "flatpak run com.xnview.XnConvert"
abbr freetube "flatpak run io.freetubeapp.FreeTube"
abbr kdiskmark "io.github.jonmagon.kdiskmark"
abbr ytdl "flatpak run me.aandrew.ytdownloader"
abbr anki "flatpak run net.ankiweb.Anki"
abbr protonup "flatpak run net.davidotek.pupgui2"
abbr lutris "flatpak run net.lutris.Lutris"
#abbr gimp "flatpak run org.gimp.GIMP"
abbr simplescan "flatpak run org.gnome.SimpleScan"
abbr signal "flatpak run org.signal.Signal"
abbr qbittorrent "flatpak run org.qbittorrent.qBittorent"
abbr vlc "flatpak run org.videolan.VLC"
#abbr okular "flatpak run org.kde.okular"
abbr lutris "DRI_PRIME 1 /usr/bin/flatpak run --branch stable --arch x86_64 --command lutris --file-forwarding net.lutris.Lutris @@u %U @@"

# CLI from Flatpaks
#alias ffmpeg="flatpak run --command=/var/lib/flatpak/app/org.videolan.VLC/current/active/files/bin/ffmpeg org.videolan.VLC"

# Stirling
alias pdf="podman run -p 8080:8080 -v /home/user/Programme/OCR:/usr/share/tesseract-ocr/4.00/tessdata frooodle/s-pdf"

# Distrobox
alias qgis="distrobox-enter Fedora39 -- env QT_QPA_PLATFORM=xcb qgis --profile default"
alias qgisvanilla="distrobox-enter Fedora39 -- env QT_QPA_PLATFORM=xcb qgis --profile showcase"
