# bubblejail
# Autogenerated from man page /usr/share/man/man1/bubblejail.1.gz
complete -c bubblejail -l debug-shell -d 'Opens a shell inside the sandbox instead of running program'
complete -c bubblejail -l dry-run -d 'Prints the bwrap and xdg-desktop-entry arguments instead of running'
complete -c bubblejail -l debug-helper-script -d 'Use the specified helper script.  This is mainly development command'
complete -c bubblejail -l debug-log-dbus -d 'Enables D-Bus proxy logging'
complete -c bubblejail -l wait -d 'Wait on the command inserted in to sandbox and get the output'
complete -c bubblejail -l debug-bwrap-args -d 'Add extra option to bwrap.  First argument will be prefixed with `--`'
complete -c bubblejail -l profile -d 'Bubblejail profile to use'
complete -c bubblejail -l no-desktop-entry -d 'Do not create desktop entry.  list [list_what]'
complete -c bubblejail -l desktop-entry -d 'Desktop entry name or path to use.  SEE ALSO'

