# buildah-source-push
# Autogenerated from man page /usr/share/man/man1/buildah-source-push.1.gz
complete -c buildah-source-push -l creds -d 'The [username[:password]] to use to authenticate with the registry if required'
complete -c buildah-source-push -l quiet -s q -d 'Suppress the progress output when pushing a source image'
complete -c buildah-source-push -l tls-verify -d 'Require HTTPS and verification of certificates when talking to container regi…'

