# buildah-login
# Autogenerated from man page /usr/share/man/man1/buildah-login.1.gz
complete -c buildah-login -l authfile -d 'Path of the authentication file'
complete -c buildah-login -l cert-dir -d 'Use certificates at path (*. crt, *. cert, *. key) to connect to the registry'
complete -c buildah-login -l compat-auth-file -d 'Instead of updating the default credentials file, update the one at path, and…'
complete -c buildah-login -l get-login -d 'Return the logged-in user for the registry'
complete -c buildah-login -l help -s h -d 'Print usage statement'
complete -c buildah-login -l password -s p -d 'Password for registry'
complete -c buildah-login -l password-stdin -d 'Take the password from stdin'
complete -c buildah-login -l tls-verify -d 'Require HTTPS and verification of certificates when talking to container regi…'
complete -c buildah-login -l username -s u -d 'Username for registry'
complete -c buildah-login -l verbose -s v -d 'print detailed information about credential store'

