# buildah-manifest-create
# Autogenerated from man page /usr/share/man/man1/buildah-manifest-create.1.gz
complete -c buildah-manifest-create -l all -d 'If any of the images which should be added to the new list or index are thems…'
complete -c buildah-manifest-create -l amend -d 'If a manifest list named listNameOrIndexName already exists, modify the preex…'
complete -c buildah-manifest-create -l tls-verify -d 'Require HTTPS and verification of certificates when talking to container regi…'

