# buildah-version
# Autogenerated from man page /usr/share/man/man1/buildah-version.1.gz
complete -c buildah-version -l help -s h -d 'Print usage statement'
complete -c buildah-version -l json -d 'Output in JSON format'

