# buildah-source-pull
# Autogenerated from man page /usr/share/man/man1/buildah-source-pull.1.gz
complete -c buildah-source-pull -l creds -d 'The [username[:password]] to use to authenticate with the registry if required'
complete -c buildah-source-pull -l quiet -s q -d 'Suppress the progress output when pulling a source image'
complete -c buildah-source-pull -l tls-verify -d 'Require HTTPS and verification of certificates when talking to container regi…'

