# buildah-info
# Autogenerated from man page /usr/share/man/man1/buildah-info.1.gz
complete -c buildah-info -l debug -s d -d 'Show additional information'
complete -c buildah-info -l format -d 'Use template as a Go template when formatting the output'

