# buildah-logout
# Autogenerated from man page /usr/share/man/man1/buildah-logout.1.gz
complete -c buildah-logout -l all -s a -d 'Remove the cached credentials for all registries in the auth file'
complete -c buildah-logout -l authfile -d 'Path of the authentication file'
complete -c buildah-logout -l compat-auth-file -d 'Instead of updating the default credentials file, update the one at path, and…'
complete -c buildah-logout -l help -s h -d 'Print usage statement'

