# buildah-add
# Autogenerated from man page /usr/share/man/man1/buildah-add.1.gz
complete -c buildah-add -l add-history -d 'Add an entry to the history which will note the digest of the added content'
complete -c buildah-add -l checksum -d 'Checksum the source content'
complete -c buildah-add -l chmod -d 'Sets the access permissions of the destination content'
complete -c buildah-add -l chown -d 'Sets the user and group ownership of the destination content'
complete -c buildah-add -l contextdir -d 'Build context directory'
complete -c buildah-add -l from -d 'Use the root directory of the specified working container or image as the roo…'
complete -c buildah-add -l ignorefile -d 'Path to an alternative . containerignore (. dockerignore) file'
complete -c buildah-add -l quiet -s q -d 'Refrain from printing a digest of the added content'
complete -c buildah-add -l retry -d 'Number of times to retry in case of failure when performing pull of images fr…'
complete -c buildah-add -l retry-delay -d 'Duration of delay between retry attempts in case of failure when performing p…'

