# buildah-source-create
# Autogenerated from man page /usr/share/man/man1/buildah-source-create.1.gz
complete -c buildah-source-create -l author -d 'Set the author of the source image mentioned in the config'
complete -c buildah-source-create -l time-stamp -d 'Set the created time stamp in the image config'

