# buildah-prune
# Autogenerated from man page /usr/share/man/man1/buildah-prune.1.gz
complete -c buildah-prune -l all -s a -d 'All local images will be removed from the system that do not have containers …'
complete -c buildah-prune -l force -s f -d 'This option will cause Buildah to remove all containers that are using the im…'

