# buildah-source-add
# Autogenerated from man page /usr/share/man/man1/buildah-source-add.1.gz
complete -c buildah-source-add -l annotation -d 'Add an annotation to the layer descriptor in the source-image manifest'

