# buildah-manifest-inspect
# Autogenerated from man page /usr/share/man/man1/buildah-manifest-inspect.1.gz
complete -c buildah-manifest-inspect -l authfile -d 'Path of the authentication file'
complete -c buildah-manifest-inspect -l tls-verify -d 'Require HTTPS and verification of certificates when talking to container regi…'

