# buildah-mkcw
# Autogenerated from man page /usr/share/man/man1/buildah-mkcw.1.gz
complete -c buildah-mkcw -l attestation-url -s u -d 'The location of a key broker / attestation server'
complete -c buildah-mkcw -l base-image -s b -d 'An alternate image to use as the base for the output image'
complete -c buildah-mkcw -l cpus -s c -d 'The number of virtual CPUs which the image expects to be run with at run-time'
complete -c buildah-mkcw -l firmware-library -s f -d 'The location of the libkrunfw-sev shared library'
complete -c buildah-mkcw -l memory -s m -d 'The amount of memory which the image expects to be run with at run-time, as a…'
complete -c buildah-mkcw -l passphrase -s p -d 'The passphrase to use to encrypt the disk image which will be included in the…'
complete -c buildah-mkcw -l slop -s s -d 'Extra space to allocate for the disk image compared to the size of the contai…'
complete -c buildah-mkcw -l type -s t -d 'The type of trusted execution environment (TEE) which the image should be mar…'
complete -c buildah-mkcw -l workload-id -s w -d 'A workload identifier which will be recorded in the container image, to be us…'

