# distrobox-enter
# Autogenerated from man page /usr/share/man/man1/distrobox-enter.1.gz
complete -c distrobox-enter -l name/-n
complete -c distrobox-enter -l /-e -s l
complete -c distrobox-enter -l no-tty/-T
complete -c distrobox-enter -l no-workdir/-nw
complete -c distrobox-enter -l additional-flags/-a
complete -c distrobox-enter -l help/-h
complete -c distrobox-enter -l root/-r -d '            way over [dq]sudo distrobox[dq] (note: if using a program other t…'
complete -c distrobox-enter -l dry-run/-d
complete -c distrobox-enter -l verbose/-v
complete -c distrobox-enter -l version/-V -d EXAMPLES

