# distrobox-assemble
# Autogenerated from man page /usr/share/man/man1/distrobox-assemble.1.gz
complete -c distrobox-assemble -l file
complete -c distrobox-assemble -l name/-n
complete -c distrobox-assemble -l replace/-R
complete -c distrobox-assemble -l dry-run/-d
complete -c distrobox-assemble -l verbose/-v
complete -c distrobox-assemble -l version/-V -d EXAMPLES
complete -c distrobox-assemble -l replace -d 'distrobox assemble create --replace [--file my/custom/path. ini] Remove'
complete -c distrobox-assemble -l dry-run -d 'This command will only print what commands distrobox would do without actuall…'

