# distrobox-create
# Autogenerated from man page /usr/share/man/man1/distrobox-create.1.gz
complete -c distrobox-create -l image/-i
complete -c distrobox-create -l name/-n
complete -c distrobox-create -l pull/-p -l yes
complete -c distrobox-create -l yes/-Y
complete -c distrobox-create -l root/-r -d '            way over [dq]sudo distrobox[dq] (note: if using a program other t…'
complete -c distrobox-create -l clone/-c -d '            this will be useful to either rename an existing distrobox or hav…'
complete -c distrobox-create -l home/-H
complete -c distrobox-create -l volume
complete -c distrobox-create -l additional-flags/-a
complete -c distrobox-create -l additional-packages/-ap
complete -c distrobox-create -l init-hooks
complete -c distrobox-create -l pre-init-hooks
complete -c distrobox-create -l init/-I -d '            this will make host[aq]s processes not visible from within the co…'
complete -c distrobox-create -l nvidia
complete -c distrobox-create -l unshare-devsys
complete -c distrobox-create -l unshare-ipc
complete -c distrobox-create -l unshare-netns
complete -c distrobox-create -l unshare-process
complete -c distrobox-create -l unshare-all
complete -c distrobox-create -l compatibility/-C
complete -c distrobox-create -l help/-h
complete -c distrobox-create -l no-entry
complete -c distrobox-create -l dry-run/-d
complete -c distrobox-create -l verbose/-v
complete -c distrobox-create -l version/-V
complete -c distrobox-create -l absolutely-disable-root-password-i-am-really-positively-sure -d 'COMPATIBILITY for a list of compatible images and container managers, please …'

