# distrobox-list
# Autogenerated from man page /usr/share/man/man1/distrobox-list.1.gz
complete -c distrobox-list -l help/-h
complete -c distrobox-list -l no-color
complete -c distrobox-list -l root/-r -d '            way over [dq]sudo distrobox[dq] (note: if using a program other t…'
complete -c distrobox-list -l verbose/-v
complete -c distrobox-list -l version/-V -d 'EXAMPLES distrobox-list You can also use environment variables to specify con…'

