# distrobox-rm
# Autogenerated from man page /usr/share/man/man1/distrobox-rm.1.gz
complete -c distrobox-rm -l all/-a
complete -c distrobox-rm -l force/-f
complete -c distrobox-rm -l rm-home
complete -c distrobox-rm -l root/-r -d '            way over [dq]sudo distrobox[dq] (note: if using a program other t…'
complete -c distrobox-rm -l help/-h
complete -c distrobox-rm -l verbose/-v
complete -c distrobox-rm -l version/-V -d 'EXAMPLES distrobox-rm container-name [--force] [--all] You can also use envir…'

