# distrobox
# Autogenerated from man page /usr/share/man/man1/distrobox.1.gz
complete -c distrobox -l file
complete -c distrobox -l name/-n
complete -c distrobox -l replace/-R
complete -c distrobox -l dry-run/-d
complete -c distrobox -l verbose/-v
complete -c distrobox -l version/-V -d EXAMPLES
complete -c distrobox -l replace -d 'distrobox assemble create --replace [--file my/custom/path. ini] Remove'
complete -c distrobox -l dry-run -d 'This command will only print what commands distrobox would do without actuall…'
complete -c distrobox -l image/-i
complete -c distrobox -l pull/-p -l yes
complete -c distrobox -l yes/-Y
complete -c distrobox -l root/-r -d '            way over [dq]sudo distrobox[dq] (note: if using a program other t…'
complete -c distrobox -l clone/-c -d '            this will be useful to either rename an existing distrobox or hav…'
complete -c distrobox -l home/-H
complete -c distrobox -l volume
complete -c distrobox -l additional-flags/-a
complete -c distrobox -l additional-packages/-ap
complete -c distrobox -l init-hooks
complete -c distrobox -l pre-init-hooks
complete -c distrobox -l init/-I -d '            this will make host[aq]s processes not visible from within the co…'
complete -c distrobox -l nvidia
complete -c distrobox -l unshare-devsys
complete -c distrobox -l unshare-ipc
complete -c distrobox -l unshare-netns
complete -c distrobox -l unshare-process
complete -c distrobox -l unshare-all
complete -c distrobox -l compatibility/-C
complete -c distrobox -l help/-h
complete -c distrobox -l no-entry
complete -c distrobox -l absolutely-disable-root-password-i-am-really-positively-sure -d 'COMPATIBILITY for a list of compatible images and container managers, please …'
complete -c distrobox -l /-e -s l
complete -c distrobox -l no-tty/-T
complete -c distrobox -l no-workdir/-nw
complete -c distrobox -l app/-a
complete -c distrobox -l bin/-b
complete -c distrobox -l delete/-d
complete -c distrobox -l export-label/-el -d '            Use [dq]none[dq] to disable'
complete -c distrobox -l export-path/-ep
complete -c distrobox -l extra-flags/-ef
complete -c distrobox -l sudo/-S
complete -c distrobox -l askpass -s A -d 'executable to stdout is used as the password input'
complete -c distrobox -l all/-a
complete -c distrobox -l icon/-i
complete -c distrobox -l user/-u
complete -c distrobox -l group/-g
complete -c distrobox -l home/-d
complete -c distrobox -l additional-packages
complete -c distrobox -l upgrade/-U
complete -c distrobox -l no-color
complete -c distrobox -l force/-f
complete -c distrobox -l rm-home
complete -c distrobox -l running

