# distrobox-upgrade
# Autogenerated from man page /usr/share/man/man1/distrobox-upgrade.1.gz
complete -c distrobox-upgrade -l help/-h
complete -c distrobox-upgrade -l all/-a
complete -c distrobox-upgrade -l running
complete -c distrobox-upgrade -l root/-r -d '            way over [dq]sudo distrobox[dq] (note: if using a program other t…'
complete -c distrobox-upgrade -l verbose/-v
complete -c distrobox-upgrade -l version/-V -d EXAMPLES

