# distrobox-host-exec
# Autogenerated from man page /usr/share/man/man1/distrobox-host-exec.1.gz
complete -c distrobox-host-exec -l help/-h
complete -c distrobox-host-exec -l verbose/-v
complete -c distrobox-host-exec -l version/-V
complete -c distrobox-host-exec -l yes/-Y -d '                            host-spawn will be installed on the guest system …'

