# distrobox-init
# Autogenerated from man page /usr/share/man/man1/distrobox-init.1.gz
complete -c distrobox-init -l name/-n
complete -c distrobox-init -l user/-u
complete -c distrobox-init -l group/-g
complete -c distrobox-init -l home/-d
complete -c distrobox-init -l help/-h
complete -c distrobox-init -l additional-packages
complete -c distrobox-init -l init/-I
complete -c distrobox-init -l pre-init-hooks
complete -c distrobox-init -l nvidia
complete -c distrobox-init -l upgrade/-U
complete -c distrobox-init -l verbose/-v
complete -c distrobox-init -l version/-V

