# distrobox-export
# Autogenerated from man page /usr/share/man/man1/distrobox-export.1.gz
complete -c distrobox-export -l app/-a
complete -c distrobox-export -l bin/-b
complete -c distrobox-export -l delete/-d
complete -c distrobox-export -l export-label/-el -d '            Use [dq]none[dq] to disable'
complete -c distrobox-export -l export-path/-ep
complete -c distrobox-export -l extra-flags/-ef
complete -c distrobox-export -l sudo/-S
complete -c distrobox-export -l help/-h
complete -c distrobox-export -l verbose/-v
complete -c distrobox-export -l version/-V -d 'You may want to install graphical applications or CLI tools in your distrobox'
complete -c distrobox-export -l askpass -s A -d 'executable to stdout is used as the password input'

