# distrobox-stop
# Autogenerated from man page /usr/share/man/man1/distrobox-stop.1.gz
complete -c distrobox-stop -l all/-a
complete -c distrobox-stop -l yes/-Y
complete -c distrobox-stop -l help/-h
complete -c distrobox-stop -l root/-r -d '            way over [dq]sudo distrobox[dq] (note: if using a program other t…'
complete -c distrobox-stop -l verbose/-v
complete -c distrobox-stop -l version/-V -d 'EXAMPLES distrobox-stop container-name1 container-name2 distrobox-stop contai…'

