# distrobox-generate-entry
# Autogenerated from man page /usr/share/man/man1/distrobox-generate-entry.1.gz
complete -c distrobox-generate-entry -l help/-h
complete -c distrobox-generate-entry -l all/-a
complete -c distrobox-generate-entry -l delete/-d
complete -c distrobox-generate-entry -l icon/-i
complete -c distrobox-generate-entry -l root/-r
complete -c distrobox-generate-entry -l verbose/-v
complete -c distrobox-generate-entry -l version/-V -d EXAMPLES

