# distrobox-ephemeral
# Autogenerated from man page /usr/share/man/man1/distrobox-ephemeral.1.gz
complete -c distrobox-ephemeral -l root/-r -d '            way over [dq]sudo distrobox[dq] (note: if using a program other t…'
complete -c distrobox-ephemeral -l verbose/-v
complete -c distrobox-ephemeral -l help/-h
complete -c distrobox-ephemeral -l /-e -s l
complete -c distrobox-ephemeral -l version/-V -d 'EXAMPLES distrobox-ephemeral --image alpine:latest -- cat /etc/os-release dis…'

